from time import sleep
from sys import executable, argv, stdout
from os import path, system, name
from subprocess import call

#To explore the full story, follow this story path including the 'Do you want to play this game' input.
#By using this as your answers or choice: Y, Y, 1, N, 2, 1,(a, 1, c), n

n_duration = 2 #2
long_n_duration = 3
sleep_before_restart = 15
very_long_duration = 4
s_duration = 0.04
s_i_duration = 0.8
incorrect_inp = f"\nSorry, your input is invalid. The game will restart in {sleep_before_restart} seconds...\nPlease be aware too that you can't press 'Enter' to skip speaking lines from the characters.\nUpon doing so, it will prompt an invalid input response and you will have to start the game again."

def colored(r, g, b, text):
    return "\033[38;2;{};{};{}m{} \033[38;2;255;255;255m".format(r, g, b, text)

def clear():
    # for windows
    if name == 'nt':
        _ = system('cls')   
    # for mac and linux(here, os.name is 'posix')
    else:
        _ = system('clear')

def speaking(s:str):
        for character in s:
                stdout.write(character)
                stdout.flush()
                sleep(s_duration)
        return " "

def incorrect_input():
        print(colored(255, 77, 77, incorrect_inp))
        sleep(sleep_before_restart)
        clear()
        call([executable, path.realpath(__file__)] + argv[1:])

clear()
title = '''\n
        ==================================
                THE ORANGE ANOMALY
        ==================================
'''
the_end = '''\n
        ===================================
                THE ORANGE ANOMALY
        ===================================
            By Christian Junel Moriones
'''

print(colored(255, 165, 0, title))

sleep(n_duration)
print(f"You were living the best life until something happened...")
sleep(n_duration)
print(f"Sleeping in the bed with your wife of 10 years, you woke up.")
sleep(n_duration)
print(f"You opened your eyes and see that everything is normal.")
sleep(n_duration)
print(f"Except for the orange lamp beside you as it is the only thing in the room that's blurry.")
sleep(n_duration)
print(f"\n\x1B[1;3mInstructions, please type the correct input as you go along with the game.\nOne wrong input and the game will restart which means you've lost.\nIt's also important to know that you can't skip the speaking lines of the characters.\nAvoid pressing the 'ENTER' key at all cost for this duration as you will be prompted to restart the game if you do so.")

start = input(f"\nDo you want to play the game?(Y/N): \x1B[0m").lower()

if start == 'y':
        print(f"\nAs you continued scanning around the room, you asked your wife: ")
        sleep(n_duration)
        print(speaking(f"\x1B[3m\"Honey? Is that orange lamp blurry to you too?\""))
        sleep(s_i_duration)
        print(speaking(f"\"It's really weird. And my head is really aching\".\x1B[0m"))
        sleep(s_i_duration)
        print(f"\nYour wife got worried when she heard this. And asks you:")
        sleep(n_duration)
        print(speaking(f"\n\x1B[3m\"Are you sure? Maybe you just need to rest more.\""))
        print(speaking(f"\"I know you've been taking care of our kids non-stop since last week.\""))
        print(speaking(f"\"If you need to rest, it's okay to tell me now.\"\x1B[0m\n"))

        decision1 = input(f"Will you follow your wife's suggestion and rest (Y/N)?: ").lower().strip()

        if decision1 == 'y':
                sleep(s_i_duration)
                print(f"\nYou have decided to sleep it off believing this weird thing will go away on its own.")
                sleep(long_n_duration)
                print(f"But before dozing off, your kids jumped at you and said if you wanted to play with them.\n")
                sleep(n_duration)

                print(f"What will you do next?")
                print(f"Action 1: Tell them you need to sleep first.")
                print(f"Action 2: Play with them.\n")
                decision3 = int(input(f"Your decision (1/2): "))
                
                if decision3 == 1:
                        sleep(s_i_duration)
                        print(f"\nYour children was disappointed but you can't help it.")
                        sleep(n_duration)
                        print(f"You asked one of them to turn off the orange lamp.")
                        sleep(n_duration)
                        print(f"They obliged but begrudgingly.")
                        sleep(n_duration)
                        print(f"Now you're asking to yourself: \n")
                        sleep(s_i_duration)
                        print(speaking(f"\n\x1B[3m\"Why is the orange lamp not blurry now?\x1B[0m\"\n"))
                        sleep(n_duration)
                        print(f"You scanned around your bedroom again and everything seems normal now.")
                        sleep(n_duration)
                        print(speaking(f"\n\x1B[3m\"Is something wrong with me?\"\x1B[0m\n"))
                        sleep(s_i_duration)
                        print(speaking(f"\x1B[3m\"Why is everything normal except for this orange lamp?\"\x1B[0m"))
                        sleep(s_i_duration)
                        print(speaking(f"\x1B[3m\"Am I getting color-blinded somehow?\"\x1B[0m\n"))
                        sleep(n_duration)
                        print(f"You're wondering. So you decided to get up and check something out.")
                        sleep(n_duration)

                        print(f"\nWould you turn on the lamp again?")               
                        decision4 = input(f"Your decision (Y/N): ").lower().strip()

                        if decision4 == 'y':
                                sleep(n_duration)
                                print(f"\nYou are now going to the orange lamp, plugged the wire, touched it, but then---")
                                sleep(very_long_duration)
                                print(f"YOU GOT ELECTRICUTED AND SUDDENLY YOU ARE \"AWAKE\" AGAIN.")
                                sleep(very_long_duration)
                                print(f"But this time, you don't know where you are.")
                                sleep(very_long_duration)
                                print(f"And then suddenly you realized you are actually on the ground.")
                                sleep(very_long_duration)
                                print(f"A bystander helped you stand up and get on your feet.")
                                sleep(n_duration)
                                print(f"You asked him: ")
                                sleep(s_i_duration)
                                print(speaking(f"\n\x1B[3m\"What the hell is happening? Where am I?!\"\x1B[0m\n"))
                                sleep(s_i_duration)
                                print(f"The bystander explained to you that you that he is actually an emergency personnel.")
                                sleep(long_n_duration)
                                print(f"Then proceeds to explain to you that you recently have been involved in an accident.")
                                sleep(long_n_duration)
                                print(f"And that accident is near a football field which you just now realized too...")
                                sleep(long_n_duration)
                                print(f"He said: ")
                                sleep(s_i_duration)
                                print(speaking(f"\n\x1B[3m\"A quarterback wearing an ORANGE jersey didn't see you while he was trying to catch the ball...\""))
                                sleep(s_i_duration)
                                print(speaking(f"\"And the collision you experienced was real hard.\"\x1B[0m\n"))
                                sleep(n_duration)
                                print(f"Apparently, you were concussed. and hurrily asked the emergency guy: ")
                                sleep(n_duration)
                                print(speaking(f"\n\x1B[3m\"Where's my wife!?\"\x1B[0m\n"))
                                sleep(s_i_duration)
                                print(f"The emergency guy was confused and said to him: ")
                                sleep(s_i_duration)
                                print(speaking(f"\n\x1B[3m\"Sir, you don't have a wife. From all the years you've been a professor in this institute--\""))
                                sleep(s_i_duration)
                                print(speaking(f"\"You were never known to have a wife or even a family...\"\x1B[0m\n"))
                                sleep(n_duration)
                                print(f"Shocked and shaking, you realized that all the 10 years...")
                                sleep(n_duration)
                                print(f"With your wife and kids, WERE NOT REAL.")
                                sleep(n_duration)
                                print(f"They simply were your brain's coping mechanism-")
                                sleep(n_duration)
                                print(f"After the collision you had with the football player.")
                                sleep(n_duration)
                                print(f"WHO IS WEARING AN ORANGE JERSEY.")
                                sleep(long_n_duration)
                                print(f"\nIn the distance you see a passing truck... ")
                                sleep(n_duration)
                                print(f"Would you run to the highway to end your life?")               
                                decision5 = input(f"Your decision (Y/N): ").lower().strip()
                                if decision5 == 'y':
                                        sleep(s_i_duration)
                                        print(f"\nSorry, you've lost.")
                                        sleep(n_duration)
                                        print(f"You see, life isn't supposed to be wasted.")
                                        sleep(n_duration)
                                        print(f"Instead of ending it, why couldn't you be more grateful that\n you have a chance to live your life to the fullest now. :)")
                                        sleep(n_duration)
                                        print(f"If you will ever have kids or already have kids, play with them whenever you can. They grow up fast you know...")
                                        sleep(very_long_duration)
                                        print(f"And lastly, there is more to life than suffering...")
                                        sleep(s_i_duration)
                                        print(colored(255, 165, 0, the_end))
                                elif decision5 == 'n':
                                        sleep(s_i_duration)
                                        print(f"\nCongratulations! You've won.")
                                        sleep(n_duration)
                                        print(f"But if you will ever have kids or already have kids, play with them whenever you can. They grow up fast too you know...")
                                        sleep(very_long_duration)
                                        print(f"\nLastly. Always choose life and that everything is\na gift you should appreciate and embrace.")
                                        sleep(5)
                                        print(colored(255, 165, 0, the_end))
                                else:
                                        incorrect_input()

                        elif decision4 == 'n':   
                                sleep(n_duration)
                                print(f"\nYou've decided not to turn it on.")
                                sleep(n_duration)
                                print(f"\nFeeling you've let your kids down, you'll decide to?")
                                print(f"\nAction 1: Nah, I'll sleep again... there's still tomorrow...")
                                print(f"Action 2: Go out the room and play with them.\n")
                                decision10 = int(input("\nYour decision (1/2): "))        

                                if decision10 == 1:
                                        sleep(s_i_duration)
                                        print(f"\nYou went back to sleep...")
                                        sleep(n_duration)
                                        print(f"You must have been really tired because you've woken up again very late at night.")
                                        sleep(n_duration)
                                        print(f"Since you slept, 8 hours have passed.")
                                        sleep(n_duration)
                                        print(f"Your wife is now beside you reading a book.")
                                        sleep(n_duration)
                                        print(f"While you are still half awake, as usual, you scanned the room.")
                                        sleep(n_duration)
                                        print(f"Just because.")
                                        sleep(n_duration)
                                        print(f"\nAnd to your shock, the orange lamp is now turned on.")
                                        sleep(n_duration)
                                        print(f"It is still very blurry in fact.")
                                        sleep(n_duration)
                                        print(f"You rubbed your eyes, scanned the room again, everything is okay, but here goes the blurry orange lamp.")
                                        sleep(very_long_duration)
                                        print(f"Starting to get irritated, you asked your wife if you can turn it off...")
                                        sleep(n_duration)
                                        print(f"She said, \"yes\".")
                                        sleep(n_duration)
                                        print(f"So there you are, getting up in bed.")
                                        sleep(n_duration)
                                        print(f"While your wife is looking at you worrily.")
                                        sleep(n_duration)
                                        print(f"\nNow, in front of you is the orange lamp.")
                                        sleep(n_duration)
                                        print(f"As you touched it to switch it off, something happened.")
                                        sleep(very_long_duration)
                                        print(f"YOU GOT ELECTRICUTED AND SUDDENLY YOU ARE \"AWAKE\" AGAIN.")
                                        sleep(very_long_duration)
                                        print(f"But this time, you don't know where you are.")
                                        sleep(very_long_duration)
                                        print(f"And then suddenly you realized you are actually on the ground.")
                                        sleep(very_long_duration)
                                        print(f"A bystander helped you stand up and get on your feet.")
                                        sleep(n_duration)
                                        print(f"You asked him: ")
                                        sleep(s_i_duration)
                                        print(speaking(f"\n\x1B[3m\"What the hell is happening? Where am I?!\"\x1B[0m\n"))
                                        sleep(s_i_duration)
                                        print(f"The bystander explained to you that you that he is actually an emergency personnel.")
                                        sleep(long_n_duration)
                                        print(f"Then proceeds to explain to you that you recently have been involved in an accident.")
                                        sleep(long_n_duration)
                                        print(f"And that accident is near a football field which you just now realized too...")
                                        sleep(long_n_duration)
                                        print(f"He said: ")
                                        sleep(s_i_duration)
                                        print(speaking(f"\n\x1B[3m\"A quarterback wearing an ORANGE jersey didn't see you while he was trying to catch the ball...\""))
                                        sleep(s_i_duration)
                                        print(speaking(f"\"And the collision you experienced was real hard.\"\x1B[0m\n"))
                                        sleep(n_duration)
                                        print(f"Apparently, you were concussed. and hurrily asked the emergency guy: ")
                                        sleep(n_duration)
                                        print(speaking(f"\n\x1B[3m\"Where's my wife!?\"\x1B[0m\n"))
                                        sleep(s_i_duration)
                                        print(f"The emergency guy was confused and said to him: ")
                                        sleep(s_i_duration)
                                        print(speaking(f"\n\x1B[3m\"Sir, you don't have a wife. From all the years you've been a professor in this institute--\""))
                                        sleep(s_i_duration)
                                        print(speaking(f"\"You were never known to have a wife or even a family...\"\x1B[0m\n"))
                                        sleep(n_duration)
                                        print(f"Shocked and shaking, you realized that all the 10 years...")
                                        sleep(n_duration)
                                        print(f"With your wife and kids, WERE NOT REAL.")
                                        sleep(n_duration)
                                        print(f"They simply were your brain's coping mechanism-")
                                        sleep(n_duration)
                                        print(f"After the collision you had with the football player.")
                                        sleep(n_duration)
                                        print(f"WHO IS WEARING AN ORANGE JERSEY.")
                                        sleep(long_n_duration)
                                        print(f"\nIn the distance you see a passing truck... ")
                                        sleep(n_duration)
                                        print(f"Would you run to the highway to end your life?")               
                                        decision11 = input(f"Your decision (Y/N): ").lower().strip()
                                        if decision11 == 'y':
                                                sleep(s_i_duration)
                                                print(f"\nSorry, you've lost.")
                                                sleep(n_duration)
                                                print(f"You see, life isn't supposed to be wasted.")
                                                sleep(n_duration)
                                                print(f"Instead of ending it, why couldn't you be more grateful that\n you have a chance to live your life to the fullest now. :)")
                                                sleep(n_duration)
                                                print(f"If you will ever have kids or already have kids, play with them whenever you can. They grow up fast you know...")
                                                sleep(very_long_duration)
                                                print(f"And lastly, there is more to life than suffering...")
                                                sleep(s_i_duration)
                                                print(colored(255, 165, 0, the_end))
                                        elif decision11 == 'n':
                                                sleep(s_i_duration)
                                                print(f"\nCongratulations! You've won.")
                                                sleep(n_duration)
                                                print(f"But if you will ever have kids or already have kids, play with them whenever you can. They grow up fast too you know...")
                                                sleep(very_long_duration)
                                                print(f"Lastly. Always choose life and that everything is\na gift you should appreciate and embrace.")
                                                sleep(long_n_duration)
                                                print(colored(255, 165, 0, the_end))
                                        else:
                                                incorrect_input()
                                elif decision10 == 2:
                                        sleep(s_i_duration)
                                        print(f"You are now having fun with your kids.") 
                                        sleep(n_duration)
                                        print(f"Oh yes, you love them to death, especially your wife.") 
                                        sleep(n_duration)
                                        print(f"She is the sunshine of your life.")
                                        print(f"\x1B[1;3m\n==== SHORT BACK STORY ====\x1B[0m")
                                        sleep(long_n_duration)
                                        print(f"\n10 years ago, as long as your memory can remember it, you met your wife for the first time.")
                                        sleep(long_n_duration)
                                        print(f"She was waiting on a bus stop with you. Surprisingly, you lived in the same neighborhood.")
                                        sleep(s_i_duration)
                                        print(f"Then the rest, as they say, is history... (｡◕‿‿◕｡)")
                                        sleep(n_duration)
                                        print(f"\x1B[1;3m\n==== BACK TO THE PRESENT ====\n\x1B[0m")
                                        sleep(n_duration)
                                        print(f"After playing with your kids, you were spent.")
                                        sleep(n_duration)
                                        print(f"Your headache comes back.")
                                        sleep(n_duration)
                                        print(f"You're thinking to yourself...\n")
                                        sleep(s_i_duration)
                                        print(speaking(f"\"Maybe I just need to drink some medicine.\""))
                                        sleep(n_duration)
                                        print(f"\nSo you went to the medicine cabinet.")
                                        sleep(n_duration)
                                        print(f"But uh-oh! Your medicine cabinet has no more pain relievers.")

                                        print(f"\nAction 1: Go to the pharmacy.")
                                        print(f"Action 2: Go back to your room to rest more.\n")
                                        decision12 = int(input("\nYour decision (1/2): ")) 

                                        if decision12 == 1:
                                                sleep(s_i_duration)
                                                print(f"\nYou get your keys on the kitchen table.")
                                                sleep(n_duration)
                                                print(f"Gone outside, and went inside your car.")
                                                sleep(n_duration)
                                                print(f"You are now driving to the pharmacy...")
                                                sleep(n_duration)
                                                print(f"Off to your peripheral vision, you see a traffic cone.")
                                                sleep(long_n_duration)
                                                print(f"You've seen a lot of traffic cones in your life.")
                                                sleep(long_n_duration)
                                                print(f"But just this one particular time, the urge to look at it is just high.")
                                                sleep(long_n_duration)
                                                print(f"You turn your head to look at it and --")
                                                sleep(n_duration)
                                                print(f"To your shock....")
                                                sleep(s_i_duration)
                                                print(f"........")
                                                sleep(s_i_duration)
                                                print(f"........")
                                                sleep(s_i_duration)
                                                print(f"........")
                                                sleep(long_n_duration)
                                                print(f"\nIt is warped, distorted, and blurry!")
                                                sleep(n_duration)
                                                print(f"\nDriving now on a panicked state, you turned around.")
                                                sleep(n_duration)
                                                print(f"Your breathing gets heavier and faster.")
                                                sleep(n_duration)
                                                print(f"Your anxiety through the roof.")
                                                sleep(n_duration)
                                                print(f"Upon arriving home, you even forgot to turn off your car.")
                                                sleep(n_duration)
                                                print(f"You ran upstairs, ignoring your wife who's cooking.")
                                                sleep(n_duration)
                                                print(f"You went to your bedroom and laid down.")
                                                sleep(n_duration)
                                                print(f"As you are looking up, you switched to your side and see the orange lamp.")
                                                sleep(n_duration)
                                                print(f"You take a big gulp, and there it is...")
                                                sleep(n_duration)
                                                print(f"\nThe orange anomaly...")
                                                sleep(n_duration)
                                                fail_count = 3
                                                while fail_count != 0:
                                                        decision13 = str(input("\nPress 'c' to check the lamp: "))
                                                        if decision13 != 'c' and fail_count >= 2:
                                                                print("\nGather up the strength, you need to turn it on!\nFor your sanity!")
                                                                fail_count -= 1
                                                        elif decision13 != 'c' and fail_count == 1:
                                                                print("You went crazy")
                                                                sleep(5)
                                                                clear()
                                                                call([executable, path.realpath(__file__)] + argv[1:])
                                                        else:
                                                                sleep(n_duration)
                                                                print(f"\nYou are now going to the orange lamp, plugged the wire, touched it, but then---")
                                                                sleep(very_long_duration)
                                                                print(f"YOU GOT ELECTRICUTED AND SUDDENLY YOU ARE \"AWAKE\" AGAIN.")
                                                                sleep(very_long_duration)
                                                                print(f"But this time, you don't know where you are.")
                                                                sleep(very_long_duration)
                                                                print(f"And then suddenly you realized you are actually on the ground.")
                                                                sleep(very_long_duration)
                                                                print(f"A bystander helped you stand up and get on your feet.")
                                                                sleep(n_duration)
                                                                print(f"You asked him: ")
                                                                sleep(s_i_duration)
                                                                print(speaking(f"\n\x1B[3m\"What the hell is happening? Where am I?!\"\x1B[0m\n"))
                                                                sleep(s_i_duration)
                                                                print(f"The bystander explained to you that you that he is actually an emergency personnel.")
                                                                sleep(long_n_duration)
                                                                print(f"Then proceeds to explain to you that you recently have been involved in an accident.")
                                                                sleep(long_n_duration)
                                                                print(f"And that accident is near a football field which you just now realized too...")
                                                                sleep(long_n_duration)
                                                                print(f"He said: ")
                                                                sleep(s_i_duration)
                                                                print(speaking(f"\n\x1B[3m\"A quarterback wearing an ORANGE jersey didn't see you while he was trying to catch the ball...\""))
                                                                sleep(s_i_duration)
                                                                print(speaking(f"\"And the collision you experienced was real hard.\"\x1B[0m\n"))
                                                                sleep(n_duration)
                                                                print(f"Apparently, you were concussed. and hurrily asked the emergency guy: ")
                                                                sleep(n_duration)
                                                                print(speaking(f"\n\x1B[3m\"Where's my wife!?\"\x1B[0m\n"))
                                                                sleep(s_i_duration)
                                                                print(f"The emergency guy was confused and said to him: ")
                                                                sleep(s_i_duration)
                                                                print(speaking(f"\n\x1B[3m\"Sir, you don't have a wife. From all the years you've been a professor in this institute--\""))
                                                                sleep(s_i_duration)
                                                                print(speaking(f"\"You were never known to have a wife or even a family...\"\x1B[0m\n"))
                                                                sleep(n_duration)
                                                                print(f"Shocked and shaking, you realized that all the 10 years...")
                                                                sleep(n_duration)
                                                                print(f"With your wife and kids, WERE NOT REAL.")
                                                                sleep(n_duration)
                                                                print(f"They simply were your brain's coping mechanism-")
                                                                sleep(n_duration)
                                                                print(f"After the collision you had with the football player.")
                                                                sleep(n_duration)
                                                                print(f"WHO IS WEARING AN ORANGE JERSEY.")
                                                                sleep(long_n_duration)
                                                                print(f"\nIn the distance you see a passing truck... ")
                                                                sleep(n_duration)
                                                                print(f"Would you run to the highway to end your life?")               
                                                                decision5 = input(f"Your decision (Y/N): ").lower().strip()
                                                                if decision5 == 'y':
                                                                        sleep(s_i_duration)
                                                                        print(f"\nSorry, you've lost.")
                                                                        sleep(n_duration)
                                                                        print(f"You see, life isn't supposed to be wasted.")
                                                                        sleep(n_duration)
                                                                        print(f"Instead of ending it, why couldn't you be more grateful that\n you have a chance to live your life to the fullest now. :)")
                                                                        sleep(n_duration)
                                                                        print(f"If you will ever have kids or already have kids, play with them whenever you can. They grow up fast you know...")
                                                                        sleep(very_long_duration)
                                                                        print(f"And lastly, there is more to life than suffering...")
                                                                        sleep(s_i_duration)
                                                                        print(colored(255, 165, 0, the_end))
                                                                        break
                                                                elif decision5 == 'n':
                                                                        sleep(s_i_duration)
                                                                        print(f"\nCongratulations! You've won.")
                                                                        sleep(n_duration)
                                                                        print(f"But if you will ever have kids or already have kids, play with them whenever you can. They grow up fast too you know...")
                                                                        sleep(very_long_duration)
                                                                        print(f"Lastly. Always choose life and that everything is\na gift you should appreciate and embrace.")
                                                                        sleep(long_n_duration)
                                                                        print(colored(255, 165, 0, the_end))
                                                                        break
                                                                else:
                                                                        incorrect_input()
                                                                        break
                                                                                            
                                        elif decision12 == 2:
                                                sleep(s_i_duration)
                                                print(f"\nYou went back to sleep...")
                                                sleep(n_duration)
                                                print(f"You must have been really tired because you've woken up again very late at night.")
                                                sleep(n_duration)
                                                print(f"Since you slept, 8 hours have passed.")
                                                sleep(n_duration)
                                                print(f"Your wife is now beside you reading a book.")
                                                sleep(n_duration)
                                                print(f"While you are still half awake, as usual, you scanned the room.")
                                                sleep(n_duration)
                                                print(f"Just because.")
                                                sleep(n_duration)
                                                print(f"\nAnd to your shock, the orange lamp is now turned on.")
                                                sleep(n_duration)
                                                print(f"It is still very blurry in fact.")
                                                sleep(n_duration)
                                                print(f"You rubbed your eyes, scanned the room again, everything is okay, but here goes the blurry orange lamp.")
                                                sleep(very_long_duration)
                                                print(f"Starting to get irritated, you asked your wife if you can turn it off...")
                                                sleep(n_duration)
                                                print(f"She said, \"yes\".")
                                                sleep(n_duration)
                                                print(f"So there you are, getting up in bed.")
                                                sleep(n_duration)
                                                print(f"While your wife is looking at you worrily.")
                                                sleep(n_duration)
                                                print(f"\nNow, in front of you is the orange lamp.")
                                                sleep(n_duration)
                                                print(f"As you touched the switch to turn it off, something happened.")
                                                sleep(very_long_duration)
                                                print(f"YOU GOT ELECTRICUTED AND SUDDENLY YOU ARE \"AWAKE\" AGAIN.")
                                                sleep(very_long_duration)
                                                print(f"But this time, you don't know where you are.")
                                                sleep(very_long_duration)
                                                print(f"And then suddenly you realized you are actually on the ground.")
                                                sleep(very_long_duration)
                                                print(f"A bystander helped you stand up and get on your feet.")
                                                sleep(n_duration)
                                                print(f"You asked him: ")
                                                sleep(s_i_duration)
                                                print(speaking(f"\n\x1B[3m\"What the hell is happening? Where am I?!\"\x1B[0m\n"))
                                                sleep(s_i_duration)
                                                print(f"The bystander explained to you that you that he is actually an emergency personnel.")
                                                sleep(long_n_duration)
                                                print(f"Then proceeds to explain to you that you recently have been involved in an accident.")
                                                sleep(long_n_duration)
                                                print(f"And that accident is near a football field which you just now realized too...")
                                                sleep(long_n_duration)
                                                print(f"He said: ")
                                                sleep(s_i_duration)
                                                print(speaking(f"\n\x1B[3m\"A quarterback wearing an ORANGE jersey didn't see you while he was trying to catch the ball...\""))
                                                sleep(s_i_duration)
                                                print(speaking(f"\"And the collision you experienced was real hard.\"\x1B[0m\n"))
                                                sleep(n_duration)
                                                print(f"Apparently, you were concussed. and hurrily asked the emergency guy: ")
                                                sleep(n_duration)
                                                print(speaking(f"\n\x1B[3m\"Where's my wife!?\"\x1B[0m\n"))
                                                sleep(s_i_duration)
                                                print(f"The emergency guy was confused and said to him: ")
                                                sleep(s_i_duration)
                                                print(speaking(f"\n\x1B[3m\"Sir, you don't have a wife. From all the years you've been a professor in this institute--\""))
                                                sleep(s_i_duration)
                                                print(speaking(f"\"You were never known to have a wife or even a family...\"\x1B[0m\n"))
                                                sleep(n_duration)
                                                print(f"Shocked and shaking, you realized that all the 10 years...")
                                                sleep(n_duration)
                                                print(f"With your wife and kids, WERE NOT REAL.")
                                                sleep(n_duration)
                                                print(f"They simply were your brain's coping mechanism-")
                                                sleep(n_duration)
                                                print(f"After the collision you had with the football player.")
                                                sleep(n_duration)
                                                print(f"WHO IS WEARING AN ORANGE JERSEY.")
                                                sleep(long_n_duration)
                                                print(f"\nIn the distance you see a passing truck... ")
                                                sleep(n_duration)
                                                print(f"Would you run to the highway to end your life?")               
                                                decision11 = input(f"Your decision (Y/N): ").lower().strip()
                                                if decision11 == 'y':
                                                        sleep(s_i_duration)
                                                        print(f"\nSorry, you've lost.")
                                                        sleep(n_duration)
                                                        print(f"You see, life isn't supposed to be wasted.")
                                                        sleep(n_duration)
                                                        print(f"Instead of ending it, why couldn't you be more grateful that\n you have a chance to live your life to the fullest now. :)")
                                                        sleep(n_duration)
                                                        print(f"And lastly, there is more to life than suffering...")
                                                        sleep(s_i_duration)
                                                        print(colored(255, 165, 0, the_end))
                                                elif decision11 == 'n':
                                                        sleep(s_i_duration)
                                                        print(f"\nCongratulations! You've won.")
                                                        sleep(n_duration)
                                                        print(f"But if you will ever have kids or already have kids, play with them whenever you can. They grow up fast too you know...")
                                                        sleep(very_long_duration)
                                                        print(f"Lastly. Always choose life and that everything is\na gift you should appreciate and embrace.")
                                                        sleep(long_n_duration)
                                                        print(colored(255, 165, 0, the_end))
                                                else:
                                                        incorrect_input()
                                        else:
                                                incorrect_input()
                                else:
                                        incorrect_input()
                        else:
                                incorrect_input()

                elif decision3 == 2:
                        sleep(s_i_duration)
                        print(f"You are now having fun with your kids.") 
                        sleep(n_duration)
                        print(f"Oh yes, you love them to death, especially your wife.") 
                        sleep(n_duration)
                        print(f"She is the sunshine of your life.")
                        print(f"\x1B[1;3m\n==== SHORT BACK STORY ====\x1B[0m")
                        sleep(long_n_duration)
                        print(f"\n10 years ago, as long as your memory can remember it, you met your wife for the first time.")
                        sleep(long_n_duration)
                        print(f"She was waiting on a bus stop with you. Surprisingly, you lived in the same neighborhood.")
                        sleep(s_i_duration)
                        print(f"Then the rest, as they say, is history... (｡◕‿‿◕｡)")
                        sleep(long_n_duration)
                        print(f"\x1B[1;3m\n==== BACK TO THE PRESENT ====\x1B[0m")
                        sleep(s_i_duration)
                        print(f"\nAfter playing with your kids, you were spent.")
                        sleep(n_duration)
                        print(f"So you asked them to turn off the orange lamp. Which is still blurry by the way...")
                        sleep(n_duration)
                        print(f"Your kids obiged happily.")
                        print(f"Now you're asking to yourself: \n")
                        sleep(s_i_duration)
                        print(speaking(f"\n\x1B[3m\"Why is the orange lamp not blurry now?\x1B[0m\"\n"))
                        sleep(n_duration)
                        print(f"You scanned around your bedroom again and everything seems normal now.")
                        sleep(n_duration)
                        print(speaking(f"\n\x1B[3m\"Is something wrong with me?\"\x1B[0m\n"))
                        sleep(s_i_duration)
                        print(f"You're wondering. So you decided to get up and check it out.")
                        sleep(n_duration)

                        print(f"\nWould you turn on the lamp again?")               
                        decision6 = input(f"Your decision (Y/N): ").lower().strip()

                        if decision6 == 'y':
                                sleep(s_i_duration)
                                print(f"\nYou are now going to the orange lamp, plugged the wire, touched it, but then---")
                                sleep(n_duration)
                                print(f"YOU GOT ELECTRICUTED AND SUDDENLY YOU ARE \"AWAKE\" AGAIN.")
                                sleep(n_duration)
                                print(f"But this time, you don't know where you are.")
                                sleep(n_duration)
                                print(f"And then suddenly you realized you are actually on the ground.")
                                sleep(n_duration)
                                print(f"A bystander helped you stand up and get on your feet.")
                                sleep(n_duration)
                                print(f"You asked him: ")
                                sleep(s_i_duration)
                                print(speaking(f"\n\x1B[3m\"What the hell is happening? Where am I?!\"\x1B[0m\n"))
                                sleep(s_i_duration)
                                print(f"The bystander explained to you that you that he is actually an emergency personnel.")
                                sleep(long_n_duration)
                                print(f"Then proceeds to explain to you that you recently have been involved in an accident.")
                                sleep(long_n_duration)
                                print(f"And that accident is near a football field which you just now realized too...")
                                sleep(long_n_duration)
                                print(f"He said: ")
                                sleep(s_i_duration)
                                print(speaking(f"\n\x1B[3m\"A quarterback wearing an ORANGE jersey didn't see you while he was trying to catch the ball...\""))
                                sleep(s_i_duration)
                                print(speaking(f"\"And the collision you experienced was real hard.\"\x1B[0m\n"))
                                sleep(n_duration)
                                print(f"Apparently, you were concussed. and hurrily asked the emergency guy: ")
                                sleep(n_duration)
                                print(speaking(f"\n\x1B[3m\"Where's my wife!?\"\x1B[0m\n"))
                                sleep(s_i_duration)
                                print(f"The emergency guy was confused and said to him: ")
                                sleep(s_i_duration)
                                print(speaking(f"\n\x1B[3m\"Sir, you don't have a wife. You are a professor in this institute.\""))
                                sleep(s_i_duration)
                                print(speaking(f"\"You were never known to have a wife or even a family...\"\x1B[0m\n"))
                                sleep(n_duration)
                                print(f"Shocked and shaking, you realized that all the 10 years...")
                                sleep(n_duration)
                                print(f"With your wife and kids, WERE NOT REAL.")
                                sleep(n_duration)
                                print(f"They simply were your brain's coping mechanism-")
                                sleep(n_duration)
                                print(f"After the collision you had with the football player.")
                                sleep(n_duration)
                                print(f"WHO IS WEARING AN ORANGE JERSEY.")
                                sleep(long_n_duration)
                                print(f"\nIn the distance you see a passing truck... ")
                                sleep(n_duration)
                                print(f"Would you run to the highway to end your life?")               
                                decision7 = input(f"Your decision (Y/N): ").lower().strip()
                                if decision7 == 'y':
                                        sleep(s_i_duration)
                                        print(f"\nSorry, you've lost.")
                                        sleep(n_duration)
                                        print(f"You see, life isn't supposed to be wasted.")
                                        sleep(n_duration)
                                        print(f"Instead of ending it, why couldn't you be more grateful that\n you have a chance to live your life to the fullest now.")
                                        sleep(n_duration)
                                        print(f"There is more to life than suffering...")
                                        sleep(very_long_duration)
                                        print(colored(255, 165, 0, the_end))
                                elif decision7 == 'n':
                                        sleep(s_i_duration)
                                        print(f"\nCongratulations! You've won.")
                                        sleep(n_duration)
                                        print(f"Not just in this game, but in life.")
                                        sleep(n_duration)
                                        print(f"Why? Because you always choose life and that everything is\na gift you should appreciate and embrace.")
                                        sleep(very_long_duration)
                                        print(colored(255, 165, 0, the_end))
                                else:
                                        incorrect_input()
                        elif decision6 == 'n':
                                print(f"You lost, sadly, you need to turn on the lamp to continue...")
                                sleep(5)
                                clear()
                                call([executable, path.realpath(__file__)] + argv[1:])
                        else:
                                incorrect_input()

                else:
                        incorrect_input()

        elif decision1 == 'n':
                sleep(s_i_duration)
                print(f"You have decided not to sleep it off and make a breakfast for her and your kids instead.")
                sleep(long_n_duration)
                print(f"Oh yes, you really love your kids very much. Your wife is the sunshine of your life.")
                sleep(long_n_duration)
                print(f"\x1B[1;3m\n==== SHORT BACK STORY ====\x1B[0m")
                sleep(long_n_duration)
                print(f"10 years ago, as long as your memory can remember it, you met your wife for the first time.")
                sleep(long_n_duration)
                print(f"She was waiting on a bus stop with you. Surprisingly, you lived in the same neighborhood.")
                sleep(s_duration)
                print(f"Then the rest, as they say, is history... (｡◕‿‿◕｡)")
                sleep(long_n_duration)
                print(f"\x1B[1;3m\n==== BACK TO THE PRESENT ====\x1B[0m")
                sleep(n_duration)
                print(f"\nYou are now making pancakes for your kids.")
                sleep(n_duration)
                print(f"But suddenly, your headache got worse. (>人<)")
                sleep(n_duration)
                print(f"You went to the medicine cabinet and looked for something that can help you.")
                sleep(n_duration)
                print(f"Sadly, you didn't. So you went back to your room to lay down instead.\n")

                sleep(n_duration)
                print(f"As you are laying down in your bed, the orange lamp is still distorted")
                sleep(n_duration)
                print(f"But everything besides it are not.")
                sleep(n_duration)
                print(f"Your books, clothes, the wall - even... looks normal.")
                sleep(n_duration)
                print(f"Feeling spooked, you get out of bed and walked to it.")
                print(f"\nWould you turn on the lamp again?")               
                decision8 = input(f"Your decision (Y/N): ").lower().strip()

                if decision8 == 'y':
                        sleep(s_i_duration)
                        print(f"\nYou are now going to the orange lamp, plugged the wire, touched it, but then---")
                        sleep(n_duration)
                        print(f"YOU GOT ELECTRICUTED AND SUDDENLY YOU ARE \"AWAKE\" AGAIN.")
                        sleep(n_duration)
                        print(f"But this time, you don't know where you are.")
                        sleep(n_duration)
                        print(f"And then suddenly you realized you are actually on the ground.")
                        sleep(n_duration)
                        print(f"A bystander helped you stand up and get on your feet.")
                        sleep(n_duration)
                        print(f"You asked him: ")
                        sleep(s_i_duration)
                        print(speaking(f"\n\x1B[3m\"What the hell is happening? Where am I?!\"\x1B[0m\n"))
                        sleep(s_i_duration)
                        print(f"The bystander explained to you that you that he is actually an emergency personnel.")
                        sleep(long_n_duration)
                        print(f"Then proceeds to explain to you that you recently have been involved in an accident.")
                        sleep(long_n_duration)
                        print(f"And that accident is near a football field which you just now realized too...")
                        sleep(long_n_duration)
                        print(f"He said: ")
                        sleep(s_i_duration)
                        print(speaking(f"\n\x1B[3m\"A quarterback wearing an ORANGE jersey didn't see you while he was trying to catch the ball...\""))
                        sleep(s_i_duration)
                        print(speaking(f"\"And the collision you experienced was real hard.\"\x1B[0m\n"))
                        sleep(n_duration)
                        print(f"Apparently, you were concussed. and hurrily asked the emergency guy: ")
                        sleep(n_duration)
                        print(speaking(f"\n\x1B[3m\"Where's my wife!?\"\x1B[0m\n"))
                        sleep(s_i_duration)
                        print(f"The emergency guy was confused and said to him: ")
                        sleep(s_i_duration)
                        print(speaking(f"\n\x1B[3m\"Sir, you don't have a wife. You are a professor in this institute.\""))
                        sleep(s_i_duration)
                        print(speaking(f"\"You were never known to have a wife or even a family...\"\x1B[0m\n"))
                        sleep(n_duration)
                        print(f"Shocked and shaking, you realized that all the 10 years...")
                        sleep(n_duration)
                        print(f"With your wife and kids, WERE NOT REAL.")
                        sleep(n_duration)
                        print(f"They simply were your brain's coping mechanism-")
                        sleep(n_duration)
                        print(f"After the collision you had with the football player.")
                        sleep(n_duration)
                        print(f"WHO IS WEARING AN ORANGE JERSEY.")
                        sleep(long_n_duration)
                        print(f"\nIn the distance you see a passing truck... ")
                        sleep(n_duration)
                        print(f"Would you run to the highway to end your life?")               
                        decision9 = input(f"Your decision (Y/N): ").lower().strip()
                        if decision9 == 'y':
                                sleep(s_i_duration)
                                print(f"\nSorry, you've lost.")
                                sleep(n_duration)
                                print(f"You see, life isn't supposed to be wasted.")
                                sleep(n_duration)
                                print(f"Instead of ending it, why couldn't you be more grateful that\n you have a chance to live your life to the fullest now.")
                                sleep(n_duration)
                                print(f"There is more to life than suffering...")
                                sleep(very_long_duration)
                                print(colored(255, 165, 0, the_end))
                        elif decision9 == 'n':
                                sleep(s_i_duration)
                                print(f"\nCongratulations! You've won.")
                                sleep(n_duration)
                                print(f"Not just in this game, but in life.")
                                sleep(n_duration)
                                print(f"Why? Because you always choose life and that everything is\na gift you should appreciate and embrace.")
                                sleep(very_long_duration)
                                print(colored(255, 165, 0, the_end))
                        else:
                                incorrect_input()
                elif decision8 == 'n':
                        print(f"You lost, sadly, you need to turn on the lamp to continue...")
                        sleep(5)
                        clear()
                        call([executable, path.realpath(__file__)] + argv[1:])
                else:
                        incorrect_input()
        else:
                incorrect_input() 

elif start == 'n':
        print(f"Thank you for your time, sadly you won't know what happened to you.")
        print(f"Closing in 3 seconds...")
        sleep(3)
        quit()
else:
        incorrect_input()


